// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package robot.commands;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.Command;
import robot.Robot;

/**
 *
 */
public class IntakeAutoRetractCmd extends Command {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    Timer captureTmr = new Timer();
    double CAPTURESETTLETIME = 0.5;
	Joystick joyCo, joyDrive;
	int state;
	String line;

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public IntakeAutoRetractCmd() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.intakeSubSys);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
    	line = "Intake Auto Retract Command Called!" ;
    	//System.out.println(line) ;
    	Robot.logger.appendLog(line);
    	joyCo= Robot.oi.coPilotJoystick;
    	joyDrive= Robot.oi.driverJoystick;
    	state = 0;
    	captureTmr.stop();
    	captureTmr.reset();
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
    	//if (joy.getPOV() == 180) {
    	//	// This is a manual override, will retract until released
    	//	Robot.intakeSubSys.retract();
    	//	return;
    	//}
    	
    	if(Robot.intakeSubSys.haveCube() == true){
    		if (state == 0) {
    			captureTmr.start();
    			state = 1;
    		}
    		if (captureTmr.get() > CAPTURESETTLETIME )
    			state = 2;
    	}
    	Robot.intakeSubSys.retract();
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
    	if (state == 2) return true;
        return false;
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
    	//Robot.intakeSubSys.retractStop();
    	Robot.intakeSubSys.hold();    	
    	line = "Intake Auto Retract Command Ended!" ;
    	//System.out.println(line) ;
    	Robot.logger.appendLog(line);
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
    	end();
    }
}
