// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package robot.commands;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import robot.Robot;
import robot.utils.Rmath;

/**
 *
 */
public class LedOnCmd extends Command {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
    private double m_value;
    private double m_TO;
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public LedOnCmd(double value, double TO) {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        m_value = value;
        m_TO = TO;

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.lEDSubSys);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
    	
		System.out.println("LedOnCmd Init value = " + m_value); 
    }	


    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
    	// noting to do here its already been done
   	
    	if (m_value == 0.99) {
    		// get value from start dashboard
    		Robot.lEDSubSys.ledsOff();
    		System.out.println("Sending LEDS OFF cmd value = " + m_value); 
    		return;
    	}    	
    	if (m_value == 999) {
    		// get value from start dashboard
    		m_value = Robot.prefs.getDouble("LEDS_10_Test_Value", m_value);
    		System.out.println("Sending TEST LEDS ON cmd value = " + m_value);     		
    	}
		System.out.println("Sending LEDS ON cmd value = " + m_value);    	
    	Robot.lEDSubSys.ledsOn(m_value);    	
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
    	m_value = 999;	// force to do test next time ???
        return true;
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
		System.out.println("LEDS ON cmd Ending !"); 
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
    	end();
    }
}
